version: '3'

services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: guestbook
        ports: [5432]
        
    redis:
        image: redis:5-alpine
        ports: [6379]